In [5]:
import numpy as np

In [53]:
#Python HW 5

#This function returns odd rows of a given array or list. 
def onlyOdd(array):
    list1 = []
    for i in array:
        counter = 0
        for j in i:
            if j%2 == 0:
                counter = 1
        if counter == 0:
            list1.append(i)
    return list1

In [55]:
arr = np.array([[1, 2, 3], [5, 7, 9], [2, 4, 6], [7, 7, 7]])
print(onlyOdd(arr))

[array([5, 7, 9]), array([7, 7, 7])]


In [101]:
#Checkers
def board():
    x = np.zeros((8,8), dtype = int)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if i%2 == 0:
                if j%2 == 0:
                    x[i][j] = 1
            elif j%2 == 1:
                x[i][j] = 1
    return x

In [103]:
print(board())

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


In [113]:
def reverse_checkerboard():
    x = np.zeros((8,8), dtype = int)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if i%2 == 1:
                if j%2 == 0:
                    x[i][j] = 1
            elif j%2 == 1:
                x[i][j] = 1
    return x

In [115]:
print(reverse_checkerboard())

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [1]:
def expansion(strArr, i):
    newArr = []
    for string in strArr:
        expanded_str = ''.join(char + ' ' * i for char in string)
        newArr.append(expanded_str.strip())
    
    return newArr

In [7]:
universe = np.array(['galaxy', 'clusters'])
expansion(universe, 2)

['g  a  l  a  x  y', 'c  l  u  s  t  e  r  s']

In [55]:
def secondLargest(planets):
    second_largest = []
    for col in range(planets.shape[1]):
        unique_values = np.unique(planets[:, col])
        if len(unique_values) < 2:
            return 'error array smaller than 2'
        else:
            second_largest.append(unique_values[-2])
    return np.array(second_largest)
    

In [57]:
planets = np.array([[192, 898, 747, 692, 914],
                    [849, 249, 370, 658, 451],
                    [802, 785, 143, 198, 616],
                    [696, 926, 269, 788, 642],
                    [583, 372, 468, 899, 911]])

print(secondLargest(planets))

[802 898 468 788 911]


[1 2 3]
1
4
7
